version: '3.9'

volumes:
  node_modules_vol:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./node_modules

services:
  biblical-translations-dev:
    image: biblical-translations-dev
    container_name: biblical-translations-dev
    build:
      context: ../.
      dockerfile: ./.devcontainer/Dockerfile
    working_dir: /biblical-translations
    volumes:
      - ..:/biblical-translations:cached
      - /var/run/docker.sock:/var/run/docker.sock
      - node_modules_vol:/biblical-translations/node_modules
    tty: true
