services:
  bible-dev:
    image: bible-dev
    container_name: bible-dev
    build:
      context: ../.
      dockerfile: ./.devcontainer/Dockerfile
    working_dir: /bible
    volumes:
      - ..:/bible:cached
    tty: true
